version: '3.5'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev
  user:
    image: user-api:v1
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - postgres
  product:
    image: product-api:v1
    ports:
      - "8081:8081"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - postgres
  shopping:
    image: shopping-api:v1
    ports:
      - "8082:8082"
    environment:
      POSTGRESS_URL: jdbc:postgresql://postgres:5432/dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PRODUCT_API_URL: http://product:8081
      USER_API_URL: http://user:8080
    depends_on:
      - postgres
  gateway: 
    image: gateway-api:v1
    ports:
      - "8084:8084"
    environment:
      SHOPPING_API_URL: http://shopping:8082
      PRODUCT_API_URL: http://product:8081
      USER_API_URL: http://user:8080